### ISSUE TITLE
Unable to install plugin from CP

### ISSUE THREAD

**Issue by RandomJo** [mediabeastnz/craft-commerce-abandoned-cart#1]
I am getting an error when I try to install your plugin from the Plugin Store section of the CP. I'm on Craft 3 and Commerce 2. I've tried installing from the beta version of Commerce 2, and I've also tried on the develop branch. Below is the error from the develop branch. When I try it back on the beta version of Commerce, it errors out, but there's nothing in the Response section.

-----------------------------

Status: Internal Server Error

Response: <!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en-US">
<head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta charset="utf-8">
    <title>⚙ Internal Server Error - Simply Inspired</title>
    <script>if (typeof Craft !== 'undefined') {
  Craft.registeredJsFiles["http://localhost:8000/cpresources/dd94b6a7/d3.js?v=1548358124"] = true;
  Craft.registeredJsFiles["http://localhost:8000/cpresources/700b0184/element-resize-detector.js?v=1548358124"] = true;
  Craft.registeredJsFiles["http://localhost:8000/cpresources/5f9baa71/jquery.js?v=1548358124"] = true;
  Craft.registeredJsFiles["http://localhost:8000/cpresources/d495aa34/jquery.mobile-events.min.js?v=1548358124"] = true;
  Craft.registeredJsFiles["http://localhost:8000/cpresources/4e145d0c/velocity.js?v=1548358124"] = true;
  Craft.registeredJsFiles["http://localhost:8000/cpresources/ee29a121/garnish.js?v=1548358124"] = true;
  Craft.registeredJsFiles["http://localhost:8000/cpresources/bdc6a9/jquery-ui.min.js?v=1548358124"] = true;
  Craft.registeredJsFiles["http://localhost:8000/cpresources/5233f2e4/jquery.payment.js?v=1548358124"] = true;
  Craft.registeredJsFiles["http://localhost:8000/cpresources/d33196f6/picturefill.js?v=1548358124"] = true;
  Craft.registeredJsFiles["http://localhost:8000/cpresources/874fbb72/selectize.js?v=1548358124"] = true;
  Craft.registeredJsFiles["http://localhost:8000/cpresources/cbd99708/jquery.fileupload.js?v=1548358124"] = true;
  Craft.registeredJsFiles["http://localhost:8000/cpresources/8d23fff8/xregexp-all.js?v=1548358125"] = true;
  Craft.registeredJsFiles["http://localhost:8000/cpresources/fb6f751f/fabric.js?v=1548358125"] = true;
  Craft.registeredJsFiles["http://localhost:8000/cpresources/81609e3b/js/Craft.min.js?v=1548358124"] = true;
  Craft.registeredJsFiles["http://localhost:8000/cpresources/60acca45/redactor.min.js?v=1548358530"] = true;
  Craft.registeredJsFiles["http://localhost:8000/cpresources/60acca45/_langs/en.js?v=1548358530"] = true;
  Craft.registeredJsFiles["http://localhost:8000/cpresources/66692bb7/customstyles.js?v=1548344208"] = true;
  Craft.registeredJsFiles["http://localhost:8000/cpresources/8b2574a/Updater.min.js?v=1548358207"] = true;
};
if (typeof Craft !== 'undefined') {
  Craft.registeredAssetBundles["carlcs\\redactorcustomstyles\\assets\\customcp\\CustomCpAsset"] = true;
  Craft.registeredAssetBundles["carlcs\\redactorcustomstyles\\assets\\redactorplugin\\RedactorPluginAsset"] = true;
  Craft.registeredAssetBundles["craft\\web\\assets\\cp\\CpAsset"] = true;
  Craft.registeredAssetBundles["craft\\web\\assets\\d3\\D3Asset"] = true;
  Craft.registeredAssetBundles["craft\\web\\assets\\elementresizedetector\\ElementResizeDetectorAsset"] = true;
  Craft.registeredAssetBundles["craft\\web\\assets\\garnish\\GarnishAsset"] = true;
  Craft.registeredAssetBundles["yii\\web\\JqueryAsset"] = true;
  Craft.registeredAssetBundles["craft\\web\\assets\\jquerytouchevents\\JqueryTouchEventsAsset"] = true;
  Craft.registeredAssetBundles["craft\\web\\assets\\velocity\\VelocityAsset"] = true;
  Craft.registeredAssetBundles["craft\\web\\assets\\jqueryui\\JqueryUiAsset"] = true;
  Craft.registeredAssetBundles["craft\\web\\assets\\jquerypayment\\JqueryPaymentAsset"] = true;
  Craft.registeredAssetBundles["craft\\web\\assets\\datepickeri18n\\DatepickerI18nAsset"] = true;
  Craft.registeredAssetBundles["craft\\web\\assets\\picturefill\\PicturefillAsset"] = true;
  Craft.registeredAssetBundles["craft\\web\\assets\\selectize\\SelectizeAsset"] = true;
  Craft.registeredAssetBundles["craft\\web\\assets\\fileupload\\FileUploadAsset"] = true;
  Craft.registeredAssetBundles["craft\\web\\assets\\xregexp\\XregexpAsset"] = true;
  Craft.registeredAssetBundles["craft\\web\\assets\\fabric\\FabricAsset"] = true;
  Craft.registeredAssetBundles["craft\\redactor\\assets\\redactor\\RedactorAsset"] = true;
  Craft.registeredAssetBundles["craft\\web\\assets\\updater\\UpdaterAsset"] = true;
};</script>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta name="referrer" content="origin-when-cross-origin">

    <link rel="apple-touch-icon" sizes="76x76" href="http://localhost:8000/cpresources/81609e3b/images/touch-icons/ipad_1x.png">
    <link rel="apple-touch-icon" sizes="120x120" href="http://localhost:8000/cpresources/81609e3b/images/touch-icons/iphone_2x.png">
    <link rel="apple-touch-icon" sizes="152x152" href="http://localhost:8000/cpresources/81609e3b/images/touch-icons/ipad_2x.png">
    <link rel="apple-touch-icon" sizes="167x167" href="http://localhost:8000/cpresources/81609e3b/images/touch-icons/ipad-pro_2x.png">
    <link rel="apple-touch-icon" sizes="180x180" href="http://localhost:8000/cpresources/81609e3b/images/touch-icons/iphone_3x.png">

    <script type="text/javascript">
        // Fix for Firefox autofocus CSS bug
        // See: http://stackoverflow.com/questions/18943276/html-5-autofocus-messes-up-css-loading/18945951#18945951
    </script>
    </head>
<body class="message ltr">
    
        <div class="message-container">
        <div id="message" class="pane">
                <h2>Internal Server Error</h2>
    <p>Server Error</p>
        </div>
    </div>
        <script type="text/javascript">
        var message = document.getElementById('message'),
            margin = -Math.round(message.offsetHeight / 2);
        message.setAttribute('style', 'margin-top: '+margin+'px !important;');
    </script>
    <script>jQuery(function ($) {
Craft.RedactorCustomStyles = {"iconSpriteUrl":"http://localhost:8000/cpresources/66692bb7/icons.svg?v=1528385795","iconIds":["textcolor","style","align","quote","money","menu","marked","label","hidden","function","favorite","clearstyles"]};
});</script>
</body>
</html>

**Comment by mediabeastnz** [comment]
@RandomJo I'll take a look at this right away for you 👍

**Comment by RandomJo** [comment]
Awesome, we've got a client who's interested in having us try it out so that'd be much appreciated.

**Comment by mediabeastnz** [comment]
Hey @RandomJo I've just tried on a fresh Craft Commerce install and it worked. Can you maybe paste a copy of your compose.json file.

**Comment by RandomJo** [comment]
We actually just upgraded to the new 2.1 release, and after doing that it installs just fine! Sorry for the false alarm. I appreciate you looking into it.

**Comment by mediabeastnz** [comment]
@RandomJo No problem
