### ISSUE TITLE
Testing for stock level in cart items

### ISSUE THREAD

**Issue by sunscreem** [mediabeastnz/craft-commerce-abandoned-cart#11]
When then items in a cart go out-of-stock, usually due to a different customer purchasing the last one, the abandoned cart is still created and scheduled emails sent.

Is there a way to check for any cart items now being out-of-stock and triggering them to be removed from the cart?

Something like a `craft->removeOutOfStockProductFromCart()` type call? Maybe one already exists?

If so, that check would need go [here](https://github.com/mediabeastnz/craft-commerce-abandoned-cart/blob/e1575c5970261643dd706cd5e5aabbb297d613b4/src/services/Carts.php#L57) and [here](https://github.com/mediabeastnz/craft-commerce-abandoned-cart/blob/e1575c5970261643dd706cd5e5aabbb297d613b4/src/services/Carts.php#L121) I think.

**Comment by mediabeastnz** [comment]
Hey @sunscreem tricky scenario as many carts might have multiple items. I'd recommend handling this on the view cart page as even though a product might be out of stock you still want the customer to come back to the site and maybe buy something else.

It could be a good way to up sell other alternatives.

Thoughts?

**Comment by sunscreem** [comment]
Yeah - true. Not sure how i'd feel as a customer to get a reminder email, to click through, to find out its sold out already though. Will have a wee think and re-open if I have a brain wave.
