### ISSUE TITLE
Problem with using custom email templates

### ISSUE THREAD

**Issue by sunscreem** [mediabeastnz/craft-commerce-abandoned-cart#13]
@mediabeastnz Guess who? AGAIN. I'm so sorry... Anyway.

I've tried everything to get my custom templates to work.

I have a custom template in my project in the usual templates folder at:

```
templates\abandoned-cart\emails\first-email.twig
```

It took me ages to find out that the queued job was running successfully but silently failing and not sending any email :( 

Eventually I found this in the queue.log:

```
2019-05-28 16:59:57 [-][-][-][error][mediabeastnz\abandonedcart\services\Carts::sendMail] Email template does not exist at “abandoned-cart/emails/first-email”.
```

So - can you help me work out why its not finding my template? 

And also why it silently fails (the queue'd job just goes away).

-rob-

**Comment by mediabeastnz** [comment]
Ahh I know why this is. The path `abandoned-cart\emails` is kind of taken by the plugin itself...

If you rename that folder and change it in the settings to something else other than that it will work.

In Craft you basically have 2 template modes and i use that path to determine it should be in control panel mode and not user templates.

Maybe try something like `emails/abandoned-cart/first-email` instead.

**Comment by sunscreem** [comment]
Yass - that's it working. 

Maybe worth adding this to the helper text on the CP fields?

**Comment by mediabeastnz** [comment]
Will do!
