### ISSUE TITLE
Blank email address?

### ISSUE THREAD

**Issue by sunscreem** [mediabeastnz/craft-commerce-abandoned-cart#14]
Hey Myles,

![image](https://user-images.githubusercontent.com/7523595/58575366-ca486680-8239-11e9-9afc-09e4506f5a11.png)

Any guesses as to way this blank email might have happened?

**Comment by mediabeastnz** [comment]
Can you please let me know what was saved in the database table for abandoned carts. I store the `orderId` and the email so I'm not sure how that would be created without an email.

I'll do some investigating my end today for you to see if someone can somehow trigger this scenario.

**Comment by mediabeastnz** [comment]
Fixed with latest release `1.1.5`. I was checking for orders with emails set to `NULL` as that's what it should be according to the database structure of Craft Commerce. I submitted a pull request on their end also but in the meant time this fix will handle both scenarios 👍
