### ISSUE TITLE
How this plug in works and question about recovered carts

### ISSUE THREAD

**Issue by sunscreem** [mediabeastnz/craft-commerce-abandoned-cart#16]
We've a non-tech person on our team asking how this plug functions. I make them some basic flow charts.

@mediabeastnz would you be so kind as to correct me if these are wrong? I've also a question below.

_get Abandoned carts_
![get Abandonded Carts (2)](https://user-images.githubusercontent.com/7523595/58657988-609e8a00-8317-11e9-86c8-e7cef96bf6e4.png)

then...

_schedule reminders_
![schedule reminders (1)](https://user-images.githubusercontent.com/7523595/58658089-a5c2bc00-8317-11e9-811a-4ceadc1cd511.png)

Finally

_send emails_
![Send Emails](https://user-images.githubusercontent.com/7523595/58658128-b70bc880-8317-11e9-9d94-730730f2b969.png)

Does all that look okay?

My next question is, lets say the first and second emails has been queued. 
The first email is sent, and the user clicks through and restores their cart.
What happens to the queued second email job?

**Comment by mediabeastnz** [comment]
Hey @sunscreem nice diagrams, that's the flow of the plugin.

Do you mind making a separate issue for your 2nd question please :)

**Comment by sunscreem** [comment]
Thank you. Good to know I'm getting my head around it :)

**Comment by sunscreem** [comment]
Last one I hope @mediabeastnz 

![image](https://user-images.githubusercontent.com/7523595/58898211-ffe5c780-86f1-11e9-80c8-061a37087e77.png)

Just checking I'm understand this last step?

**Comment by sunscreem** [comment]
Sorry for the awful "flow charts". Rubbish software I'm using.
