### ISSUE TITLE
Email not sending

### ISSUE THREAD

**Issue by RandomJo** [mediabeastnz/craft-commerce-abandoned-cart#2]
I have installed your plugin on my staging site, and I can see that things are working to some degree, but the actual email never appears to have sent. I can see in my cron log that the emails get added to the queue:
```
Feb 27 17:54:01 app.fpm.sim-stage cron.ctrl: Start cart-email-sched
Feb 27 17:54:02 app.fpm.sim-stage cron.cart-email-sched: Abandoned Cart: Finding carts
Feb 27 17:54:02 app.fpm.sim-stage cron.cart-email-sched: Carts Found: 2
Feb 27 17:54:02 app.fpm.sim-stage cron.cart-email-sched: Abandoned Cart: Job completed
Feb 27 17:54:02 app.fpm.sim-stage cron.ctrl: Done cart-email-sched
```

And then in the queue log, I can see that the send function was run:
```
2019-02-27 11:54:03 [-][-][-][info][craft\queue\QueueLogBehavior::afterExec]  [8340] Send abandoned cart reminder (attempt: 1) - Done (time: 1.144s)
```

But, I haven't received an email and I've checked SendGrid for evidence of the email being sent and there's nothing there. I know that email works generally because I tested that earlier today. What do you think I'm missing?

**Comment by mediabeastnz** [comment]
Hey @RandomJo, if the sending failed for any reason there would definitely be something in the logs (I'm catching and returning all steps of the send mail process).

I'll just triple check a fresh install and make sure it's sending. I use malign but that shouldn't make any difference.

**Comment by mediabeastnz** [comment]
@RandomJo the plugin is definitely sending emails. Maybe your queue hasn't been triggered yet?
If you look in the dashboard this will give you a good insight into the status of each cart.

By default the email will be pushed to the queue and have a delay of 1hr.

If you have any suggestions on how to improve the visibility of this, submit a feature request here and I'll see what I can do.

**Comment by RandomJo** [comment]
The dashboard says the emails have sent, but I didn't receive them and SendGrid has no record of them. It does, however, have records of the test emails I sent through Craft to make sure emails were working generally.

Here's my view of the dashboard with email addresses obfuscated: https://www.evernote.com/l/AT98kWRs9h5A0J1kB0kIwZdapbRnOjrA3QU

And here's my view of our SendGrid activity:
https://www.evernote.com/l/AT_ZX8U5PktIaYLmUDLyrdkhQJwG83vwU4A

If it helps at all, for email settings I'm using SMTP through SendGrid.

I feel like I must be missing something silly, but I'm not sure what else to try because it looks like everything's going correctly (no errors in any of the logs related to your plugin), but the emails just aren't getting sent for me.

**Comment by mediabeastnz** [comment]
@RandomJo thinks for the screenshots, are you able to send me a copy of your logs as well? Maybe there's something in there that might help me pinpoint what's going on.

**Comment by RandomJo** [comment]
Sure, no problem!

When I run `php craft abandoned-cart/reminders/schedule-emails`, I see:
```
Abandoned Cart: Finding carts
Carts Found: 2
Abandoned Cart: Job completed
```

When I run `php craft queue/run` queue, there is no output.

This is all see in queue.log when I search for "abandoned" (appears several times):
```
2019-02-27 14:36:06 [-][-][-][info][mediabeastnz\abandonedcart\AbandonedCart::init] Abandoned Cart for Craft Commerce 2 plugin loaded
```

Let me know if you think anything in web.log or console.log would be helpful. I searched "abandoned" and didn't see anything in those. I also searched "email" and "mail," and it it looks like it's printing as a field being asked for in a SELECT query but nothing else.

**Comment by RandomJo** [comment]
Are you on the Craft Discord? I'd be happy to talk in real time there if that would be helpful.

**Comment by mediabeastnz** [comment]
@RandomJo sure am - message me at mediabeastnz

**Comment by mediabeastnz** [comment]
@RandomJo are you happy if I mark this as closed? 

Emails are sending correctly right? I just need to better document the delays/queues better.

**Comment by RandomJo** [comment]
I'm still doing some testing. I got tied up on my end the last few days so haven't been able to confirm everything is working as expected now. I'll be able to get back to you in a day or two.

**Comment by RandomJo** [comment]
This is working as expected. I just had some misunderstandings about how everything worked. The extra documentation should clear things up. Thank you!

**Comment by mediabeastnz** [comment]
@RandomJo thanks for the feedback and testing - I'll update the documentation to make things clearer in the next release 👍
