### ISSUE TITLE
[Question] Email template overrides

### ISSUE THREAD

**Issue by 23d1** [mediabeastnz/craft-commerce-abandoned-cart#21]
Where does the plugin check for email template overrides? I'm assuming `craft/templates/emails` is where it checks before defaulting to `vendor/mediabeastnz/craft-commerce-abandoned-cart/src/templates/emails`. Just confirming instead of looking into the source code.

Edit: Closing — didn't realize it was a setting all along. Just got back to building some ecommerce. My bad!

**Comment by mediabeastnz** [comment]
@23d1 haha no stress, just sing out if you have any questions.
