### ISSUE TITLE
How to setup CRON

### ISSUE THREAD

**Issue by chadcrowell** [mediabeastnz/craft-commerce-abandoned-cart#22]
Hi there, great plugin. I am looking for a little help. I have a VPS with about 10 sites on it. site1.com uses your plugin.

Setting up CRON jobs does not occur at the site level, like you might do for an account in WHM/cPanel. There is 1 CRON config area for the entire server. So this:

*/1 * * * *  php craft queue/run

Doesn't tell the server which site to run it on. Should I be specifying something like this?

*/1 * * * *  php craft /home/site1.com/path/to/your/plugin/queue/run

or something else? I realize you don't know my server, but with a little direction, if you know, I can probably get it figured out.

**Comment by mediabeastnz** [comment]
You're on the right track I'd expect that 2nd one to be how you do it on a VPS. 

Id send a quick support request to your provider to see if you path is correct, saves time consuming debugging :)
