### ISSUE TITLE
Confusion over the dashboard

### ISSUE THREAD

**Issue by sunscreem** [mediabeastnz/craft-commerce-abandoned-cart#25]
Hi Myles,

![image](https://user-images.githubusercontent.com/7523595/60437521-74832780-9c06-11e9-87a6-a920f2c77210.png)

Can you help me explain whats happening here? A few questions:

- Why are some carts showing "view" and some have "-"
- Why are some email addresses clickable and some not?
- Why do some carts have totals and others not?

**Comment by mediabeastnz** [comment]
Hey @sunscreem this happens when the original order is no longer there (for whatever reason).
I'll investigate this more to see if there's anything I can do to avoid this.

I'll leave this open for now

**Comment by mediabeastnz** [comment]
1.3.1 should resolve this.

**Comment by sunscreem** [comment]
@mediabeastnz Applied this update and all good now. Thank you.
