### ISSUE TITLE
Weird issue immediately after a deploy

### ISSUE THREAD

**Issue by sunscreem** [mediabeastnz/craft-commerce-abandoned-cart#26]
Hi Myles,

After we deploy a site, the first time a user clicks a (valid) link to recover a cart, the restore seems to work, but the forward to the cart then throws a 500. 

It very confusing as our bug tracking software isn't throwing an error when this happens. 

Click the link again and everything works.

I went down a bit of rabbit hole and I've got as far as finding that rows in the `craft_elements` table are being soft-deleted which may or may not be related.

Any ideas?

**Comment by mediabeastnz** [comment]
Are you able to send me your logs or the 500 error response please.

**Comment by sunscreem** [comment]
Will do, probably a few days as I'm away just now.

**Comment by sunscreem** [comment]
Myles - i'll close this and come back to it if the issue re-appears.
