### ISSUE TITLE
Session issue with load balanced environment

### ISSUE THREAD

**Issue by skoften** [mediabeastnz/craft-commerce-abandoned-cart#27]
We've setup this plugin, but gettin this error:

![Screenshot 2019-07-18 at 11 10 16](https://user-images.githubusercontent.com/1286410/61444977-c210cb80-a94c-11e9-8f06-c93ff33f4ac5.jpg)

We're running our commerce site on 3 webservers (lighttpd) behind 1 loadbalancer (nginx ). Can this have something do to with it?

**Comment by mediabeastnz** [comment]
I wonder if that is related to this issues https://github.com/craftcms/cms/issues/2798

Are you able to send me the stack trace for that and ill do some investigating.

**Comment by skoften** [comment]
In which file can I find the stacktrace? I've searched queue.log and web.log for keyword "abandoned", but no stacktrace found.

Also, during development I had the plugin set to test mode, which seem to work fine. After adding them to my cronjob this error first came up.

**Comment by skoften** [comment]
PS. I tried reinstalling it to remove some old data, but for some reason it won't accept the licence key anymore. The input field doesn't respond very well, and when I can add the code, it's doesn't update.

![Screenshot 2019-07-19 at 10 12 32](https://user-images.githubusercontent.com/1286410/61520185-eda7ba80-aa0d-11e9-9069-b4f0f8b8abc1.jpg)

**Comment by mediabeastnz** [comment]
Hey @skoften yeah there should be a stack trace in one of those - maybe search for the error itself e.g. "session does not exist".

Have you created a custom template for abandoned carts? If so it could be that it can't find it or an assets within it.

Once I have the stack trace I can dig a little deeper 🙏
