### ISSUE TITLE
Bob Lazar

### ISSUE THREAD

**Issue by thejoshsmith** [mediabeastnz/craft-commerce-abandoned-cart#28]
Robert Lazar (1959–) is a double-edged sword of UFO cranks. On the one hand, he's a pathological liar with a long laundry list of fantasies about working at Area 51. On the other hand, he runs United Nuclear, one of the very few chemical supply houses still supplying as many unrestricted chemicals as possible to amateur chemists. Make of him what you will, but if you need fifty feet of magnesium ribbon, a neodymium magnet the size of a brick (for, I don't know, wiping credit cards from ten feet away?), or a jar of heavy water, he's your best source.

**Comment by mediabeastnz** [comment]
👽
