### ISSUE TITLE
No possibility of applying settings in a php config file

### ISSUE THREAD

**Issue by tomdeleu** [mediabeastnz/craft-commerce-abandoned-cart#29]
### Feature request

Most plugins allow for settings to be applied in a .php config file (/config folder)

This possibility doesn't seem to exist in this plugin. Could be very handy in multi environment setups, to define test mode only in dev environment for example.

**Comment by mediabeastnz** [comment]
Good idea! I will try and put it in the next release this week :)

**Comment by mattsbanner** [comment]
Hi @mediabeastnz 

We're currently building a site with this plugin running across 3 environments and this would be really useful to us.

Is this something we might see soon?

Thanks 😄

**Comment by mediabeastnz** [comment]
Support for environment settings is supported in version `1.6.0`
