### ISSUE TITLE
Feature Request: URL that triggers looking for abandoned carts and sending emails accordingly

### ISSUE THREAD

**Issue by 23d1** [mediabeastnz/craft-commerce-abandoned-cart#3]
Any chance of having a URL function as the trigger looking for abandoned cart and sending emails accordingly? Could be a button as well, on the plugin page.

The reason I ask is because in some situations you might not have access to cron and want to use an online cron service that just visits a URL, or even triggering from the admin panel with the push of a button. Perhaps even one for checking and one for sending.

**Comment by mediabeastnz** [comment]
Hey @23d1, this feature is already in progress. It's especially helpful for developers when trying the plugin out. Should be release in the next week or two.

**Comment by 23d1** [comment]
Fantastic! I'll keep an eye out.

**Comment by mediabeastnz** [comment]
@23d1 I've just release a new [version](https://github.com/mediabeastnz/craft-commerce-abandoned-cart/releases/tag/1.1.0) that lets you manually check for abandoned carts from the dashboard. This basically does the same as a cron job  ✌️
