### ISSUE TITLE
Abandoned Carts Lists

### ISSUE THREAD

**Issue by dawb** [mediabeastnz/craft-commerce-abandoned-cart#31]
It would be handy to have the ability to export the list of customers and the products that they were ordering from the abandoned carts area.

Also having the ability to navigate between the lists of carts within this area would be good so you can access more that the last 14 carts.

**Comment by mediabeastnz** [comment]
Pagination is enabled so you should be able to view quite a few per page.

As for your first feature request - that's quite a big feature and isn't on the roadmap for version 1 at least. Feel free to leave more information in regards to how you see this working though.

**Comment by mediabeastnz** [comment]
@dawb release `1.4.0` has a temporary feature to help with this. On the dashboard there's now an export button which simply shows all records as a json list (which you can use import into your own CSV etc).

It includes basic order and cart item details as well as customer email ✌️
