### ISSUE TITLE
Is it possible to disable second reminder?

### ISSUE THREAD

**Issue by fantasticmachine** [mediabeastnz/craft-commerce-abandoned-cart#33]
Is it possible to only send 1 reminder? How can I disable the second reminder?

I've tried leaving the time field blank, setting it to 0, or setting it to a huge number and it tells me the value has to be between 12 and 48 hours.
How can I disable it?

**Comment by mediabeastnz** [comment]
That's not currently a feature but would be a pretty easy thing to add. I'll see if I can squeeze it in for the next release :)

**Comment by mediabeastnz** [comment]
@fantasticmachine sorry for the delay on this... you can now disable this via settings in the `1.4.0` release ✌️

Disabling it basically just skips any attempt to schedule and send the 2nd email as well as showing a disabled status on the dashboard for the column.
