### ISSUE TITLE
Queue Error

### ISSUE THREAD

**Issue by billythekid** [mediabeastnz/craft-commerce-abandoned-cart#34]
Hi, I have the abandoned cart plugin on a craft 3.4/commerce3 site and as recommended by craft moved the queue runners to a daemon.

I'm now getting this error in the queue manager (/admin/utilities/queue-manager/{queuid}) for "Send abandoned cart reminder" jobs

`Undefined variable: secondReminderDisabled `

Job data is:
```json
{
    "cartId": 336,
    "reminder": 2,
    "description": null
}
```

Is this something on my end or something in the plugin?

Cheers

PHP version 	7.3.6
Craft edition & version 	Craft Pro 3.4.8
Abandoned Cart for Craft Commerce 2 	1.4.0
Craft Commerce 	3.0.11

**Comment by mediabeastnz** [comment]
Will check this out now @billythekid

**Comment by mediabeastnz** [comment]
All sorted @billythekid

**Comment by billythekid** [comment]
Brilliant, I've applied the fix and the queue runs. Thanks very much.
