### ISSUE TITLE
[FR] Fire Events

### ISSUE THREAD

**Issue by billythekid** [mediabeastnz/craft-commerce-abandoned-cart#35]
I was wondering if we could maybe get a couple of events fired from the plugin, in particular when an AbandonedCart is `save()`d so that we can hook into this and prevent the save (or amend it)

My particular use-case is that my automated testing of the checkout process on the production server is creating abandoned carts (because we're not completing them) and this is muddying the conversion numbers. Ideally I could listen to the onBeforeSave event for the test email address or whatever and prevent the abandoned cart being created.

I was thinking the abandoned cart models may have been elements and inherited this automatically but had a quick look in the code and see they're not.

**Comment by mediabeastnz** [comment]
@billythekid 😬 I'm actually in the process of making them into Elements as they come with lots of features, it's just a lot of work to implement - it's in progress though!

In the meantime I can easily add a few events like the one you mention.

An alternative to this is I add the feature that allows you to "blacklist" emails from triggering the plugin?

**Comment by billythekid** [comment]
Yeah I think that might be a good idea for non-devs too. That way they could prevent their own tests from screwing with the numbers.

It would definitely meet my use-case above.

**Comment by mediabeastnz** [comment]
Easy, leave it with me

**Comment by mediabeastnz** [comment]
Released in version 1.5.3 ✌️

You can add a comma separated list of emails under settings and they will be ignored.

**Comment by billythekid** [comment]
Nice one, cheers!

**Comment by billythekid** [comment]
Heya @mediabeastnz,

I'm still getting abandoned carts for blacklisted email addresses. Can you take a look please?
<img width="1747" alt="Screenshot 2020-04-16 at 18 02 26" src="https://user-images.githubusercontent.com/330170/79485012-763ea000-800c-11ea-9e33-0423c648a0a9.png">

<img width="1569" alt="Screenshot_2020-04-16_at_17_55_48" src="https://user-images.githubusercontent.com/330170/79485008-750d7300-800c-11ea-99d4-fc5c3adaad93.png">

**Comment by mediabeastnz** [comment]
@billythekid this is definitely working as expected using the latest version.

**Comment by joshuapease** [comment]
Some events would be super helpful for a client need that we have. 

Manually adding emails to the blacklist isn't an option for our client, so we're hoping to build a an automated way for users to add their emails to a list (we'd build our own custom controllers / records to store the blocked emails). 

If we had access to some events before save or email send, we could check our custom blacklist and prevent saving or sending from happening.

Wanted to see if this is something you've already made progress on, or if you're open to a possible PR (I "might" be able to free up some time at work). 

Appreciate your plugin. Cheers!

**Comment by joshuapease** [comment]
It dawned on me that records emit events. 

I'm going to attempt creating my own dynamic list of blocked emails and invalidate the `AbandonedCart` record if exists in the list. 

```php
use mediabeastnz\abandonedcart\records\AbandonedCart as AbandonedCartRecord;

Event::on(
    AbandonedCartRecord::class,
    AbandonedCartRecord::EVENT_BEFORE_INSERT,
    function (ModelEvent $event) {
        // TODO invalidate if the record email
        // matches our list of blocked emails.
        $event->isValid = false;
    }
);
```
