### ISSUE TITLE
Failed to sent reminder

### ISSUE THREAD

**Issue by skoften** [mediabeastnz/craft-commerce-abandoned-cart#37]
![Screenshot 2020-06-13 at 10 11 39](https://user-images.githubusercontent.com/1286410/84587766-654eb700-ae22-11ea-9f63-b229e4546708.jpg)
![Screenshot 2020-06-13 at 10 11 35](https://user-images.githubusercontent.com/1286410/84587768-67b11100-ae22-11ea-90cc-067bd4e2d814.jpg)

I tried changing the php session to the database via app.php, no effect, same errors.

Craft CMS 3.4.22, using a systemd as queue worker

**Comment by mediabeastnz** [comment]
Thanks @skoften i'll take a look

**Comment by skoften** [comment]
Any update on this? Still having this issue on a daily base :-(

**Comment by mediabeastnz** [comment]
@skoften sorry I haven't had much time to work on this recently 😬

Are you able to send me a sample of your logs file so i can see where this is failing as I can't replicate.

**Comment by skoften** [comment]
Sure, queue.log: https://pastebin.com/0EWi1zwe

**Comment by mediabeastnz** [comment]
@skoften Can you please send me your `abandoned-cart-second.html` file?

**Comment by skoften** [comment]
I've sent them by email!

**Comment by mediabeastnz** [comment]
@skoften Based on the logs you sent me, it looks like something in your templates is calling a function that is uses `Session`. This can't be used via the console and will through an error.

I believe it might be might the line 
```
{% set cart = craft.commerce.carts.cart %}
```

If you don't need to use `cart` i would just remove that line.

**Comment by skoften** [comment]
Nice, removed it and now it works. Thanks!
