### ISSUE TITLE
Missing Class Error

### ISSUE THREAD

**Issue by mikeymeister** [mediabeastnz/craft-commerce-abandoned-cart#4]
I have installed the plugin but I am having difficulties getting the emails to send. In the queue table of the database, my SendEmailReminder job shows a failed status with the error message:
`Class 'mediabeastnz\abandonedcart\models\CartRecord' not found`
Looking in the logs the full message is:
`Error: Class 'mediabeastnz\abandonedcart\models\CartRecord' not found in /ProjectPath/vendor/mediabeastnz/craft-commerce-abandoned-cart/src/models/AbandonedCart.php:115`

If I import the cartRecord class to the model file (`use mediabeastnz\abandonedcart\records\AbandonedCart as CartRecord;`), the emails send as expected. As this error hasn't been listed before, I can only assume the current release has been working correctly for others. I wonder if there is some other problem in my installation that meant it would not send the email reminders until I made the above change?

**Comment by mediabeastnz** [comment]
Hey @mikeymeister i'll take a look with a fresh install and see if I can replicate.

**Comment by mediabeastnz** [comment]
@mikeymeister thanks for reporting this one, it turns out that classes was removed in version 1.1.1. I've added it back in and published a new version so everyone can quickly update. 

I've also added your feature request #5 as it was a great idea!
