### ISSUE TITLE
Allow non-admin users to access Settings

### ISSUE THREAD

**Issue by iamtompickering** [mediabeastnz/craft-commerce-abandoned-cart#42]
Would it be possible to allow non-admin users to access the settings of this plugin?

My client would like to update the discount code using their account, but a message comes up saying they are not authorised. 

I have checked in the user permissions, but there aren't any options to allow them access. I do not want to make their account a full admin either.

**Comment by mediabeastnz** [comment]
This feature exists in 2.0.1
