### ISSUE TITLE
Abandoned Cart stopped working

### ISSUE THREAD

**Issue by bhashkar007** [mediabeastnz/craft-commerce-abandoned-cart#49]
I have setup Abandoned Cart plugin and it was working fine. But unfortunately, it stopped working since a couple of weeks. Could you please help. 
I am using:
PHP v7.4.4
Craft Commerce v3.2.8.1
Abandoned Cart v1.6.2

**Comment by mediabeastnz** [comment]
What do you mean by "stopped working"?

I've tested these exact versions and it's working as expected.

Is there any additional information you can give me?

**Comment by mediabeastnz** [comment]
Duplicate #47
