### ISSUE TITLE
Configurable cart redirect

### ISSUE THREAD

**Issue by mikeymeister** [mediabeastnz/craft-commerce-abandoned-cart#5]
It would be good if the redirect in the restore cart action (BaseController) was configurable so a secondary redirect was not necessary to send the user to somewhere other than /shop/cart.

**Comment by mediabeastnz** [comment]
Can you give me an example of what you'd like the restore cart action to do?

**Comment by mikeymeister** [comment]
Thanks for the quick reply.
I may have over complicated my comment. After it restores the cart, the controller redirects to /shop/cart. On our sites we often use /basket instead, for example. It would be good if we could define our cart url in the plugin. Thanks.
