### ISSUE TITLE
Change currency of totals

### ISSUE THREAD

**Issue by iamtompickering** [mediabeastnz/craft-commerce-abandoned-cart#50]
Is it possible to change the currency of the total values in the dashboard area? 

E.g. Total Recovered and Recovered This Month.

The order prices are showing as GBP, but Total Recovered and Recovered This Month are showing as USD.

**Comment by mediabeastnz** [comment]
The individual orders can be placed in different currencies so they are being returned "as is" so to speak.

The "Total Recovered and Recovered This Month" are using the stores base currency.

Is your base currency USD?
