### ISSUE TITLE
Support custom mailer component

### ISSUE THREAD

**Issue by samhibberd** [mediabeastnz/craft-commerce-abandoned-cart#56]
Hi @mediabeastnz, we use a custom mailer component to handle all emails, would love it if you could support this by using the loaded mailer config to compose the new message.

I think you would just need to replace the `$newEmail = new Message();` here:

https://github.com/mediabeastnz/craft-commerce-abandoned-cart/blob/27a7c5ade8cdb9338e4b15a3888c04cf3be26f07/src/services/Carts.php#L325-L329

with:

`$newEmail = Craft::$app->getMailer()->compose();`

**Comment by mediabeastnz** [comment]
Done in 2.0.1
