### ISSUE TITLE
Send abandoned cart reminder showing as "Delayed" in Queue Manager

### ISSUE THREAD

**Issue by celexus** [mediabeastnz/craft-commerce-abandoned-cart#58]
I have a 20 abandoned cart reminders sitting in my Queue Manager showing as "Delayed" - how do I solve this issue ? 
Why would an abandoned cart reminder email end up as "Delayed" ? 

![Capture](https://user-images.githubusercontent.com/6831255/132323510-daf68cff-3074-488e-b029-b300cb01714f.PNG)

**Comment by mediabeastnz** [comment]
This is how jobs are sent to the queue. Those emails are likely scheduled to be sent in 1hr or 12 hours using the default settings.
