### ISSUE TITLE
Email Blacklist Event

### ISSUE THREAD

**Issue by samhibberd** [mediabeastnz/craft-commerce-abandoned-cart#59]
Hey, would you be open to a PR or willing to add an event that would allow us to add emails to the blacklisted emails stored in the plug-in settings, before they are used in the abandoned cart query?

We need to support unsubscribing directly from emails, and project config makes this tricky to implement as a direct update of the plugin settings.

**Comment by mediabeastnz** [comment]
This can be done using environment variables is that makes it easier for you? Otherwise I can look to add an event that would allow other developers to tap into the the blacklist.

**Comment by samhibberd** [comment]
An event would be awesome, fairly high traffic site and the list is growing (we currently are using env vars).

Many thanks.

**Comment by joshparylak** [comment]
@mediabeastnz We have the same use case here, we need to support unsubscribing directly from emails. Any idea when/if this ability is being added?

**Comment by samhibberd** [comment]
@mediabeastnz see this PR https://github.com/mediabeastnz/craft-commerce-abandoned-cart/pull/74 fixes this would be great to see this implemented so we can handle unsubscribe / exclusions ourselves!

**Comment by mediabeastnz** [comment]
Thanks to @lenvanessen this can now be done via an event.

```
Event::on(
    Carts::class,
    Carts::EVENT_BEFORE_MAIL_SEND,
    function (BeforeMailSend $event) {
        // implement
    }
);
```
