### ISSUE TITLE
Re-installation fails with no error

### ISSUE THREAD

**Issue by sunscreem** [mediabeastnz/craft-commerce-abandoned-cart#6]
Because of reasons, I had the plug in installed, then uninstalled. When I re-installed it I couldn't activate it from the CP. The error was just "cannot activate plug in".

Running the activation from the command line showed that it was failing because the abandoned cart table already existed in the database.

Might be an idea to handle that?

**Comment by mediabeastnz** [comment]
Hi @sunscreem I'll take a look, thanks for loggin an issue.

**Comment by mediabeastnz** [comment]
Hey @sunscreem I've uninstalled and reinstalled multiple times to see if it can get it to fail but it works fine each time. Are you uninstalling and installing via the control panel?

**Comment by sunscreem** [comment]
Yeah - so with this one I think what happened was a weird screw up that I caused. I installed the plug in, then compose removed it without uninstalling it first - so the abandoned cart table was still present.

My suggestion is that, on install, if the abandoned cart table is present you dump it and start over? At the moment it fails silently (except for the craft log file)

**Comment by mediabeastnz** [comment]
Good call - I'll look to add this feature in an up-coming release.
