### ISSUE TITLE
Plans to support Commerce 4?

### ISSUE THREAD

**Issue by terryupton** [mediabeastnz/craft-commerce-abandoned-cart#62]
Are there any plans for this plugin to support Commerce 4? 
I am considering implementing for a client tin their existing commerce 3 setup, but I don't want this to become a future blocker to Commerce 4.

**Comment by sunscreem** [comment]
Hey @mediabeastnz - just wondering if you have any thoughts on this?

**Comment by sunscreem** [comment]
Hey @mediabeastnz  - Any thoughts on this one - I'm keen to get a Craft 4 update completed :)

**Comment by mediabeastnz** [comment]
Hey @sunscreem sorry yes. I've started updating my plugins. Sorry time on these plugins are limited these days...

**Comment by mediabeastnz** [comment]
Support added as of 2.0.0
