### ISSUE TITLE
48 hour limitation

### ISSUE THREAD

**Issue by pxel** [mediabeastnz/craft-commerce-abandoned-cart#66]
Hi,

Wondering if there is a way to bypass, or increase the 48 hour limitation for:

a) The 2nd email delay
b) The link expiry

Is using an environment variable a way to bypass the validation in the plugin settings for this? 
If so, what (if any) implications are there for doing this?

Thanks so much!

**Comment by mediabeastnz** [comment]
Hello,

Yes you can disable the 2nd reminder in settings or increase/decrease when it's triggered.
