### ISSUE TITLE
View RAW Data hyperlink triggering PHP Notice

### ISSUE THREAD

**Issue by tommy-ball** [mediabeastnz/craft-commerce-abandoned-cart#68]
My client's ecommerce site uses the Abandoned Cart plugin to send email reminders to their users. On January 10th, they reported that the View RAW Data hyperlink was no longer functioning properly (see screenshot).

Any idea how to get this data export to begin working again? Thanks in advance!

### Screenshots
![image](https://user-images.githubusercontent.com/108827998/218569408-c80a2298-92c2-4cd7-9543-0d659ebc3905.png)

**Comment by mediabeastnz** [comment]
Looks like it's because a product might have been deleted since. I've added a check to prevent this in the latest release.

**Comment by tommy-ball** [comment]
Hi @mediabeastnz, thanks for the update! However it looks like your release was just for Craft 4. Our client is still on Craft 3...any way you could apply the update to Craft 3 as well? Thank you!!
