### ISSUE TITLE
Question about usage/testing

### ISSUE THREAD

**Issue by sunscreem** [mediabeastnz/craft-commerce-abandoned-cart#7]
Hello again, Can I ask how to test this is working?

Plug in installed, added some items to my basket, waited an hour, but nothing happened and nothing is showing up in the CP?

**Comment by mediabeastnz** [comment]
Hey @sunscreem can you give me more details on the version you're using please. 

There are a couple ways to test, first one is to click the "check for abandoned carts" button in the CMS (note this would require an item to be in your cart for at least 1hr) the next is to get the cron job up and running which basically does the same as the previous option.

When i'm testing I actually change the "date modified" column in the database on the particular order. That saves me having to wait an hour.

**Comment by sunscreem** [comment]
Hey, I've installed the latest version (1.1.2.1) on craft 3.1.25 and commerce is 2.1.5.2.

Being super lazy, as I could go and read your code, but can you run through how the process works? I see that all carts on the site are actually orders that aren't completed. So I'm guessing when the command runs it looks for anything over a certain time that needs marked as abandoned? They reason I ask is I start the checkout process at 6pm last night, manually ran the "find abandoned carts" at 11am this morning and it found nothing. Is there a limit on the age that manual search looks at?

**Comment by mediabeastnz** [comment]
@sunscreem yeah so it wont look back further than 12 hours. Ideally you'd want your system checking quite often via a cron job so all new orders are detected asap. Heres's a quick overview of what's happening:

Firstly the plugin checks to see if any orders are still in progress e.g. not complete and if they have been for more than 1hr the system will add it to the abandoned cart table (as long as it has a value of >$0.00).

This is when the delay times come into play. If you leave them as the defaults the first email will be sent 1hr after being added to that table. E.g. 2 hours since it became an order.

After that if no action was taken on the first email the 2nd email will be sent X hours later.

Does that make sense? If possible i'd get a cron up and running as per the docs as this the easiest way to test.

**Comment by sunscreem** [comment]
@mediabeastnz Thank you again sir - that all makes complete sense now :)

**Comment by sunscreem** [comment]
Hi @mediabeastnz. Just finishing off testing on this and having (yet another) question.

Here's how I'm testing things:

1. Add some items to basket and partially complete the checkout with email address.

2. Edit the craft_order table entry, both the `created_at` and `updated_at` to about 2 hours ago.

3. Run `./craft abandoned-cart/reminders/schedule-emails` manually from the CLI. 

4. Note that cart is now showing in the dashboard and the abandoned-carts table. Woohoo.

5. I think change the updated and create time of the order in the *abandoned-carts* table to about 5 hours ago. I have my 1st email to be sent set to 3 hours. I run the `./craft abandoned-cart/reminders/schedule-emails` and `./craft queue/run`. Nothing happens. No email sent.

I tried changing the created at and updated at times on the original craft_orders row too but still nothing. Can you let me know what step I'm missing to force the 1st (and 2nd) emails to be sent?

**Comment by mediabeastnz** [comment]
Hey @sunscreem great to here they're going into that table now. Does the dashboard say the first email is queued?

If you set the delay to 3hrs it will be put into the queue table with a run time of +3hrs.
You're best to set it to something rather low while testing.

**Comment by mediabeastnz** [comment]
@sunscreem any luck? I've got this working on multiple sites so would love to get yours up and running :)

**Comment by sunscreem** [comment]
Hey @mediabeastnz I've been dragged off onto other projects. I'll close this for now and re-open if I get any more issues. Hoping to get this into production early next week all being well.

**Comment by sunscreem** [comment]
@mediabeastnz Woo-Hoo - its all working. Just waiting on approval from the client now. I may have to come back to you with a feature request - I've not tested this yet but does it handle out of stock products that are auto-removed from the site? For example, if there is an item with only 1 available, and another customer purchases it, how does you plug in handle that? 

Again - I'm being lazy - I need to go and look at your code.

**Comment by sunscreem** [comment]
I'll open a fresh issue for this.
