### ISSUE TITLE
How do I install this for Commerce and Craft 3?

### ISSUE THREAD

**Issue by terryupton** [mediabeastnz/craft-commerce-abandoned-cart#70]
When I try and run `composer require mediabeastnz/craft-commerce-abandoned-cart -w && php craft plugin/install abandoned-cart` I get the following error:

 Problem 1
    - Root composer.json requires mediabeastnz/craft-commerce-abandoned-cart ^2.0 -> satisfiable by mediabeastnz/craft-commerce-abandoned-cart[2.0.0, 2.0.1, 2.0.2].
    - mediabeastnz/craft-commerce-abandoned-cart[2.0.0, ..., 2.0.2] require craftcms/cms ^4.0.0 -> found craftcms/cms[4.0.0, ..., 4.3.10] but it conflicts with your root composer.json require (3.7.67).

How can I install this for a current Commerce/Craft 3 project?
Thanks.

**Comment by mediabeastnz** [comment]
Hi @terryupton try the 1.6.6 release which is 1.x version of this plugin that supports Craft 3.
