### ISSUE TITLE
Make columns 'orderable' on  Abandoned Carts > Dashboard

### ISSUE THREAD

**Issue by terryupton** [mediabeastnz/craft-commerce-abandoned-cart#83]
### What are you trying to do?

It would be a nice to be able to order the columns on Abandoned Carts > Dashboard screen.
This would also bring parity with Craft as this is possible on element index screens. 

the main benefit of this is that the carts are ordered by date from the oldest first, so even just reversing this order would be a huge benefit.

### What's your proposed solution?

Ability to click the table headers and update the order (toggle) similar to the native craft functionality for ordering entries etc.

**Comment by engram-design** [comment]
I'll see what we can do here, but as these aren't elements, and we use the `Craft.VueAdminTable` component, I _don't believe they're sortable. I believe that's only possible if the content of the table is lazy-loaded, which probably isn't a bad idea anyway.

Revamped for the next release. To get this early, run `composer require verbb/abandoned-cart:"dev-craft-4 as 3.0.0"` or `composer require verbb/abandoned-cart:"dev-craft-5 as 4.0.0"`.

**Comment by terryupton** [comment]
Thanks Josh.

**Comment by engram-design** [comment]
Added in [3.0.1](https://github.com/verbb/abandoned-cart/releases/tag/3.0.1)
