### ISSUE TITLE
Settings not storing ENV Variables for Restore Link Expiry, 1st Reminder Delay and 2nd Reminder Delay

### ISSUE THREAD

**Issue by terryupton** [mediabeastnz/craft-commerce-abandoned-cart#85]
### Describe the bug

After updating to v3.0.0 following the take over the plugin.
I had a client contact to sat that the second reminder emails were getting trigged 5 minutes after the first email.

After checking the settings locally I noticed that the stored ENV vars for:
- Restore Link Expiry
- 1st Reminder Delay
- 2nd Reminder Delay

These settings had been removed and the fields were blank.
Upon trying to add the ENV settings back into the fields, I get presented with the error that the fields are empty and the VARS are removed.  

The fields are ok and hold the VARS for;
- Discount Code
- Blacklisted Emails

<img width="2178" alt="Screenshot 2024-11-14 at 15 44 22" src="https://github.com/user-attachments/assets/5e7d69f5-03bc-4a12-bcde-93b70adf30bf">

### Steps to reproduce

1. Go in to the settings 
2.try to add a ENV_variable for Restore Link Expiry, 1st Reminder Delay and 2nd Reminder Delay
3. try to save the settings
4. Errorrs and the setting is not maintained.

### Craft CMS version

Craft Pro 4.12.9

### Plugin version

3.0.0

### Multi-site?

No

**Comment by engram-design** [comment]
Fixed in [3.0.1](https://github.com/verbb/abandoned-cart/releases/tag/3.0.1)
